version: '3'
services:
  web-server-alexa-gilon:
    build: './Docker/Server/'
    container_name: alexa_jilon

    volumes:
      - ./dist/:/var/www/html/
    ports:
      - "8102:80"
    stdin_open: true
    tty: true
